In [1]:
#今日は面倒くさいからirisのデータセットでいきます

In [11]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [12]:
df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
df.isnull().sum() #欠損値なしを確認

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [16]:
LE = LabelEncoder()
df["Species"] = LE.fit_transform(df["Species"])
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [17]:
df.tail()

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

In [21]:
X = df.drop("Species", axis=1)
y = df["Species"]
X.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [18]:
KN = KNeighborsClassifier(n_neighbors=5) #近傍点はとりあえず5とかで

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size = 0.3, random_state = 0)

KN.fit(X_train, y_train)

KNeighborsClassifier()

In [20]:
from sklearn.metrics import accuracy_score

y_pred = KN.predict(X_test)
y_train_pred = KN.predict(X_train)

print("トレーニングデータの正答率：", accuracy_score(y_train, y_train_pred))
print("モデルの正答率：", accuracy_score(y_pred, y_test))

トレーニングデータの正答率： 1.0
モデルの正答率： 1.0

In [ ]:
#最高の予測モデルやな（笑）
#もしやどこかミスしている？？