In [2]:
#データ操作に着目してpandasの基本操作をまとめます
import pandas as pd

In [3]:
#weather.csvの読み込み

In [5]:
df = pd.read_csv("weather.csv")
df

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [6]:
#読み込んだデータの確認
#先頭10行
#末尾10行

In [7]:
head10 = df.head(10)
head10

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [8]:
tail10 = df.tail(10)
tail10

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
356,3.4,15.0,0.8,4.8,11.7,S,70.0,S,S,35.0,...,24,1023.4,1023.1,1,5,8.3,14.3,No,0.0,No
357,3.2,18.0,0.0,7.4,12.2,SSE,48.0,SSE,S,26.0,...,25,1026.6,1022.8,1,2,9.1,16.3,No,0.0,No
358,0.9,20.7,0.0,5.4,8.4,NNW,39.0,SSE,N,2.0,...,29,1023.2,1018.4,3,8,9.4,19.1,No,0.0,No
359,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,4.0,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [9]:
#不要な行・列の削除=必要な特定行・列の抽出

In [10]:
df.columns #一旦カラムを全表示させてみる

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [12]:
#仮に先頭3列と末尾3列を削除してみる。上記から特定項目を消すだけ
#というより必要な項目を残すとも言える
df[['Evaporation', 
    'Sunshine',
    'WindGustDir', 
    'WindGustSpeed', 
    'WindDir9am', 
    'WindDir3pm',
    'WindSpeed9am', 
    'WindSpeed3pm', 
    'Humidity9am', 
    'Humidity3pm',
    'Pressure9am', 
    'Pressure3pm', 
    'Cloud9am', 
    'Cloud3pm', 
    'Temp9am',
    'Temp3pm']]

,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
0,3.4,6.3,NW,30.0,SW,NW,6.0,20,68,29,1019.7,1015.0,7,7,14.4,23.6
1,4.4,9.7,ENE,39.0,E,W,4.0,17,80,36,1012.4,1008.4,5,3,17.5,25.7
2,5.8,3.3,NW,85.0,N,NNE,6.0,6,82,69,1009.5,1007.2,8,7,15.4,20.2
3,7.2,9.1,NW,54.0,WNW,W,30.0,24,62,56,1005.5,1007.0,2,7,13.5,14.1
4,5.6,10.6,SSE,50.0,SSE,ESE,20.0,28,68,49,1018.3,1018.5,7,7,11.1,15.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,7.6,12.1,NNW,76.0,SSE,NW,7.0,50,38,15,1016.1,1010.8,1,3,20.4,30.0
362,11.6,12.7,N,48.0,NNW,NNW,2.0,19,45,22,1020.0,1016.9,0,1,17.2,28.2
363,8.4,5.3,ESE,43.0,ENE,ENE,11.0,9,63,47,1024.0,1022.8,3,2,14.5,18.3
364,5.0,7.1,NW,46.0,SSW,WNW,6.0,28,69,39,1021.0,1016.2,6,7,15.8,25.9
365,6.0,12.6,NW,78.0,NW,WNW,31.0,35,43,13,1009.6,1009.2,1,1,23.8,28.6

In [13]:
#データ型、サイズ、列名、行名を確認

In [14]:
#データ型
df.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [15]:
#サイズ
df.shape

(366, 22)

In [16]:
#列名
df.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [17]:
#行名
df.index

RangeIndex(start=0, stop=366, step=1)

In [18]:
#任意の要素を取得する

In [19]:
#5～10行目、3～6列目の要素を取得
df.iloc[4:10, 2:6]

   Rainfall  Evaporation  Sunshine WindGustDir
4       2.8          5.6      10.6         SSE
5       0.0          5.8       8.2          SE
6       0.2          4.2       8.4          SE
7       0.0          5.6       4.6           E
8       0.0          4.0       4.1           S
9      16.2          5.4       7.7           E

In [20]:
#people.csvを読み込み、df_peopleと定義

In [25]:
df_people = pd.read_csv("people.csv")
df_people
#なんやこのデータセット

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55   NaN        k
11   us  155    50  44.0        k
12   us  160    58  39.0        k
13   us  162    59   NaN        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90  23.0        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [24]:
#df_peopleから、ulke = us

In [27]:
df_people[df_people["ulke"] == "us"]

   ulke  boy  kilo   yas cinsiyet
9    us  185   105  33.0        e
10   us  165    55   NaN        k
11   us  155    50  44.0        k
12   us  160    58  39.0        k
13   us  162    59   NaN        k
14   us  167    62  55.0        k

In [29]:
df_people.query("ulke == 'us'")

   ulke  boy  kilo   yas cinsiyet
9    us  185   105  33.0        e
10   us  165    55   NaN        k
11   us  155    50  44.0        k
12   us  160    58  39.0        k
13   us  162    59   NaN        k
14   us  167    62  55.0        k

In [30]:
#boy > 130を抽出

In [31]:
df_people[df_people["boy"] > 130]

   ulke  boy  kilo   yas cinsiyet
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55   NaN        k
11   us  155    50  44.0        k
12   us  160    58  39.0        k
13   us  162    59   NaN        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90  23.0        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [32]:
df_people.query("boy > 130")

   ulke  boy  kilo   yas cinsiyet
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55   NaN        k
11   us  155    50  44.0        k
12   us  160    58  39.0        k
13   us  162    59   NaN        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90  23.0        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [33]:
#150 > boy >130 の抽出

In [34]:
df_people[(df_people["boy"] < 150) & (df_people["boy"] > 130)]

  ulke  boy  kilo   yas cinsiyet
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k

In [35]:
#df_peopleのユニークな値(固有値)の抽出

In [36]:
#.uniqueメソッドを使用するが、このメソッドはSeries型にのみ適用⇒カラム一つずつを指定してやる
df_people["ulke"].unique()

array(['tr', 'us', 'fr'], dtype=object)

In [37]:
df_people["boy"].unique()

array([130, 125, 135, 133, 129, 180, 190, 175, 177, 185, 165, 155, 160,
       162, 167, 174, 193, 187, 183, 159, 164, 166], dtype=int64)

In [38]:
#df_peopleのulke列に対し、重複のある値のある行を削除したdfを取得

In [39]:
#.drop_duplicatesを使用する
df_people.drop_duplicates(subset="ulke")
#subset = None の場合は全カラムで全一致した場合のみ重複とみなす

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
9    us  185   105  33.0        e
15   fr  174    70  47.0        e

In [40]:
#カラム名を変更　ulkeを国籍に変更

In [42]:
df_people.columns

Index(['ulke', 'boy', 'kilo', 'yas', 'cinsiyet'], dtype='object')

In [49]:
df_people.columns = ['国籍', 'boy', 'kilo', 'yas', 'cinsiyet']
df_people

    国籍  boy  kilo   yas cinsiyet
0   tr  130    30  10.0        e
1   tr  125    36  11.0        e
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k
4   tr  129    38  12.0        e
5   tr  180    90  30.0        e
6   tr  190    80  25.0        e
7   tr  175    90  35.0        e
8   tr  177    60  22.0        k
9   us  185   105  33.0        e
10  us  165    55   NaN        k
11  us  155    50  44.0        k
12  us  160    58  39.0        k
13  us  162    59   NaN        k
14  us  167    62  55.0        k
15  fr  174    70  47.0        e
16  fr  193    90  23.0        e
17  fr  187    80  27.0        e
18  fr  183    88  28.0        e
19  fr  159    40  29.0        k
20  fr  164    66  32.0        k
21  fr  166    56  42.0        k

In [51]:
df_people = df_people.rename(columns={"boy":"男の子"})
df_people

    国籍  男の子  kilo   yas cinsiyet
0   tr  130    30  10.0        e
1   tr  125    36  11.0        e
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k
4   tr  129    38  12.0        e
5   tr  180    90  30.0        e
6   tr  190    80  25.0        e
7   tr  175    90  35.0        e
8   tr  177    60  22.0        k
9   us  185   105  33.0        e
10  us  165    55   NaN        k
11  us  155    50  44.0        k
12  us  160    58  39.0        k
13  us  162    59   NaN        k
14  us  167    62  55.0        k
15  fr  174    70  47.0        e
16  fr  193    90  23.0        e
17  fr  187    80  27.0        e
18  fr  183    88  28.0        e
19  fr  159    40  29.0        k
20  fr  164    66  32.0        k
21  fr  166    56  42.0        k

In [52]:
#dfの並び替え　男の子を昇順に直す

In [53]:
df_people.sort_values("男の子")

    国籍  男の子  kilo   yas cinsiyet
1   tr  125    36  11.0        e
4   tr  129    38  12.0        e
0   tr  130    30  10.0        e
3   tr  133    30   9.0        k
2   tr  135    34  10.0        k
11  us  155    50  44.0        k
19  fr  159    40  29.0        k
12  us  160    58  39.0        k
13  us  162    59   NaN        k
20  fr  164    66  32.0        k
10  us  165    55   NaN        k
21  fr  166    56  42.0        k
14  us  167    62  55.0        k
15  fr  174    70  47.0        e
7   tr  175    90  35.0        e
8   tr  177    60  22.0        k
5   tr  180    90  30.0        e
18  fr  183    88  28.0        e
9   us  185   105  33.0        e
17  fr  187    80  27.0        e
6   tr  190    80  25.0        e
16  fr  193    90  23.0        e

In [54]:
#降順だと
df_people.sort_values("男の子", ascending=False)

    国籍  男の子  kilo   yas cinsiyet
16  fr  193    90  23.0        e
6   tr  190    80  25.0        e
17  fr  187    80  27.0        e
9   us  185   105  33.0        e
18  fr  183    88  28.0        e
5   tr  180    90  30.0        e
8   tr  177    60  22.0        k
7   tr  175    90  35.0        e
15  fr  174    70  47.0        e
14  us  167    62  55.0        k
21  fr  166    56  42.0        k
10  us  165    55   NaN        k
20  fr  164    66  32.0        k
13  us  162    59   NaN        k
12  us  160    58  39.0        k
19  fr  159    40  29.0        k
11  us  155    50  44.0        k
2   tr  135    34  10.0        k
3   tr  133    30   9.0        k
0   tr  130    30  10.0        e
4   tr  129    38  12.0        e
1   tr  125    36  11.0        e

In [55]:
#ダニー変数への変換　df_peopleの国籍列をダミー変数へ

In [57]:
pd.get_dummies(df_people, columns=["国籍"])

    男の子  kilo   yas cinsiyet  国籍_fr  国籍_tr  国籍_us
0   130    30  10.0        e      0      1      0
1   125    36  11.0        e      0      1      0
2   135    34  10.0        k      0      1      0
3   133    30   9.0        k      0      1      0
4   129    38  12.0        e      0      1      0
5   180    90  30.0        e      0      1      0
6   190    80  25.0        e      0      1      0
7   175    90  35.0        e      0      1      0
8   177    60  22.0        k      0      1      0
9   185   105  33.0        e      0      0      1
10  165    55   NaN        k      0      0      1
11  155    50  44.0        k      0      0      1
12  160    58  39.0        k      0      0      1
13  162    59   NaN        k      0      0      1
14  167    62  55.0        k      0      0      1
15  174    70  47.0        e      1      0      0
16  193    90  23.0        e      1      0      0
17  187    80  27.0        e      1      0      0
18  183    88  28.0        e      1      0      0
19  159    40  29.0        k      1      0      0
20  164    66  32.0        k      1      0      0
21  166    56  42.0        k      1      0      0

In [58]:
#dfの欠損値を確認する

In [59]:
df

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [60]:
df.isnull() #欠損値無いんかい

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
362,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
363,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
364,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
365,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [61]:
#欠損値の補完

In [62]:
df.fillna(0) #欠損値ないからどこも補完していない

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [64]:
df.dropna(axis=1) #欠損値がないからどこも消えてないけどな

,MinTemp,MaxTemp,Rainfall,Evaporation,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,17,80,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,28,68,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,50,38,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,19,45,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,9,63,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,28,69,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,35,43,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [65]:
#ユニークな値と出現回数 iris.csvより

In [67]:
df_iris = pd.read_csv("iris.csv")
df_iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [68]:
#Speciesを確認しようじゃないか
df_iris["Species"].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: Species, dtype: int64

In [69]:
#各クラスごとの集計
#Iris-virginica,Iris-setosa,Iris-versicolorそれぞれの
#SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCmの平均値

In [71]:
df_iris.groupby("Species").mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [72]:
#統計量の算出

In [73]:
#df_irisの各カラムごとの平均値、中央値、最大値、最小値、標準偏差を算出
df_iris.mean()
df_iris.median()
df_iris.max()
df_iris.min()
df_iris.std()

Id               43.445368
SepalLengthCm     0.828066
SepalWidthCm      0.433594
PetalLengthCm     1.764420
PetalWidthCm      0.763161
dtype: float64

In [74]:
df_iris.describe() #最強

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [77]:
#相関係数の算出

In [82]:
#MinTempとEvaporation
df[["MinTemp", "Evaporation"]].corr()

             MinTemp  Evaporation
MinTemp      1.00000      0.64993
Evaporation  0.64993      1.00000

In [83]:
df.corr() #全部に対して表示！

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
MinTemp,1.000000,0.752471,0.201939,0.649930,0.035711,0.218020,0.127542,-0.065922,-0.207897,-0.040709,-0.501707,-0.498007,0.215776,0.118397,0.916745,0.722730,0.218551
MaxTemp,0.752471,1.000000,-0.073560,0.690026,0.452064,0.109672,-0.216814,-0.167873,-0.359602,-0.533327,-0.290883,-0.379394,-0.175730,-0.135991,0.870604,0.989261,0.027557
Rainfall,0.201939,-0.073560,1.000000,-0.007293,-0.150990,0.096190,0.219637,0.056008,0.150109,0.289013,-0.331581,-0.250218,0.180046,0.127792,0.077299,-0.087493,0.089860
Evaporation,0.649930,0.690026,-0.007293,1.000000,0.318025,0.288477,0.068929,0.048601,-0.519587,-0.391780,-0.381906,-0.391093,-0.106007,-0.100045,0.707676,0.671632,0.076762
Sunshine,0.035711,0.452064,-0.150990,0.318025,1.000000,0.095843,-0.064522,0.072573,-0.499017,-0.759429,0.006276,-0.036201,-0.681092,-0.661131,0.219509,0.470447,-0.378823
WindGustSpeed,0.218020,0.109672,0.096190,0.288477,0.095843,1.000000,0.527653,0.693945,-0.349793,-0.069439,-0.540180,-0.526885,-0.012666,0.050230,0.256223,0.072501,0.251991
WindSpeed9am,0.127542,-0.216814,0.219637,0.068929,-0.064522,0.527653,1.000000,0.472966,-0.270623,0.146657,-0.356332,-0.247952,0.101842,-0.022471,0.064074,-0.235186,0.039091
WindSpeed3pm,-0.065922,-0.167873,0.056008,0.048601,0.072573,0.693945,0.472966,1.000000,-0.266092,-0.026368,-0.359800,-0.337325,-0.026426,0.007207,-0.017766,-0.187570,-0.009447
Humidity9am,-0.207897,-0.359602,0.150109,-0.519587,-0.499017,-0.349793,-0.270623,-0.266092,1.000000,0.546718,0.135727,0.134420,0.392842,0.271938,-0.436551,-0.355119,0.165931
Humidity3pm,-0.040709,-0.533327,0.289013,-0.391780,-0.759429,-0.069439,0.146657,-0.026368,0.546718,1.000000,-0.087946,-0.010052,0.551633,0.510108,-0.255681,-0.581676,0.358752
Pressure9am,-0.501707,-0.290883,-0.331581,-0.381906,0.006276,-0.540180,-0.356332,-0.359800,0.135727,-0.087946,1.000000,0.967895,-0.157553,-0.141000,-0.460418,-0.253674,-0.290584
Pressure3pm,-0.498007,-0.379394,-0.250218,-0.391093,-0.036201,-0.526885,-0.247952,-0.337325,0.134420,-0.010052,0.967895,1.000000,-0.128944,-0.143837,-0.492636,-0.345485,-0.311421
Cloud9am,0.215776,-0.175730,0.180046,-0.106007,-0.681092,-0.012666,0.101842,-0.026426,0.392842,0.551633,-0.157553,-0.128944,1.000000,0.525218,0.021041,-0.202344,0.273914
Cloud3pm,0.118397,-0.135991,0.127792,-0.100045,-0.661131,0.050230,-0.022471,0.007207,0.271938,0.510108,-0.141000,-0.143837,0.525218,1.000000,0.040945,-0.172814,0.326455
Temp9am,0.916745,0.870604,0.077299,0.707676,0.219509,0.256223,0.064074,-0.017766,-0.436551,-0.255681,-0.460418,-0.492636,0.021041,0.040945,1.000000,0.844406,0.164842
Temp3pm,0.722730,0.989261,-0.087493,0.671632,0.470447,0.072501,-0.235186,-0.187570,-0.355119,-0.581676,-0.253674,-0.345485,-0.202344,-0.172814,0.844406,1.000000,-0.005825
RISK_MM,0.218551,0.027557,0.089860,0.076762,-0.378823,0.251991,0.039091,-0.009447,0.165931,0.358752,-0.290584,-0.311421,0.273914,0.326455,0.164842,-0.005825,1.000000